# Generated by Django 4.1.7 on 2023-08-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('PayPal', 'PayPal')], max_length=100),
        ),
    ]
